baseURL = "http://peteryin.fyi/"
languageCode = "en-us"
title = "Peter Yin"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  dark = "off"
  copyright = "© 2021. Site powered by Hugo and the Etch theme"
  highlight = true

#[menu]
#  [[menu.main]]
#    identifier = "posts"
#    name = "posts"
#    title = "posts"
#    url = "/posts"
#    weight = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true